services:
  wordpress_db:
    image: mysql:5.5
    platform: linux/amd64
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql

  wordpress:
    image: wordpress:4.7.0
    restart: always
    ports:
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
